import { NetworkMap } from './types'

/** Topologia inicial quando nao ha SQLite ou mapa vazio (apenas demonstracao). */
export const INITIAL_MAPS: NetworkMap[] = [
  {
    id: 'local',
    name: 'Local',
    devices: [
      {
        id: 'd1',
        label: 'POP 01',
        ip: '192.168.1.1',
        icon: 'tower',
        status: 'online',
        x: 120,
        y: 100,
        latency: 4,
        uptime: 99.8,
        mapId: 'local',
        comment: 'Demo',
      },
      {
        id: 'd2',
        label: 'POP 02',
        ip: '192.168.1.2',
        icon: 'tower',
        status: 'online',
        x: 320,
        y: 80,
        latency: 8,
        uptime: 98.5,
        mapId: 'local',
      },
      {
        id: 'd3',
        label: 'POP 03',
        ip: '192.168.1.3',
        icon: 'router-antenna',
        status: 'online',
        x: 160,
        y: 220,
        latency: 12,
        uptime: 97.2,
        mapId: 'local',
      },
      {
        id: 'd4',
        label: 'POP 04',
        ip: '192.168.1.4',
        icon: 'router-antenna',
        status: 'offline',
        x: 340,
        y: 220,
        latency: undefined,
        uptime: 45.3,
        mapId: 'local',
        comment: 'Exemplo offline',
      },
      {
        id: 'd5',
        label: 'POP 05',
        ip: '192.168.1.5',
        icon: 'tower',
        status: 'online',
        x: 500,
        y: 160,
        latency: 5,
        uptime: 99.1,
        mapId: 'local',
      },
      {
        id: 'd6',
        label: 'POP 06',
        ip: '192.168.1.6',
        icon: 'tower',
        status: 'offline',
        x: 600,
        y: 60,
        latency: undefined,
        uptime: 60.0,
        mapId: 'local',
      },
      {
        id: 'd7',
        label: 'POP 07',
        ip: '192.168.1.7',
        icon: 'router',
        status: 'offline',
        x: 720,
        y: 60,
        latency: undefined,
        uptime: 55.0,
        mapId: 'local',
      },
      {
        id: 'd8',
        label: 'POP 08',
        ip: '192.168.1.8',
        icon: 'switch',
        status: 'warning',
        x: 840,
        y: 60,
        latency: 320,
        uptime: 78.0,
        mapId: 'local',
      },
      {
        id: 'd9',
        label: 'POP 09',
        ip: '192.168.1.9',
        icon: 'tower',
        status: 'offline',
        x: 700,
        y: 240,
        latency: undefined,
        uptime: 40.0,
        mapId: 'local',
      },
      {
        id: 'd10',
        label: 'POP 10',
        ip: '192.168.1.10',
        icon: 'tower',
        status: 'online',
        x: 120,
        y: 340,
        latency: 9,
        uptime: 99.5,
        mapId: 'local',
      },
      {
        id: 'd11',
        label: 'POP 11',
        ip: '192.168.1.11',
        icon: 'access-point',
        status: 'online',
        x: 360,
        y: 350,
        latency: 15,
        uptime: 96.8,
        mapId: 'local',
      },
      {
        id: 'd12',
        label: 'POP 12',
        ip: '192.168.1.12',
        icon: 'tower',
        status: 'online',
        x: 540,
        y: 380,
        latency: 18,
        uptime: 95.0,
        mapId: 'local',
      },
    ],
    submapNodes: [
      {
        id: 'sn-norte',
        label: 'Sub-rede Norte',
        x: 900,
        y: 180,
        mapId: 'local',
        targetMapId: 'submap-norte',
      },
    ],
    badges: [],
    links: [
      { id: 'l1', sourceId: 'd1', targetId: 'd3', mapId: 'local', capacity: '1g', rxBps: 0, txBps: 0 },
      { id: 'l2', sourceId: 'd2', targetId: 'd4', mapId: 'local', capacity: '1g', rxBps: 0, txBps: 0 },
      { id: 'l3', sourceId: 'd3', targetId: 'd4', mapId: 'local', capacity: '10g', rxBps: 0, txBps: 0 },
      { id: 'l4', sourceId: 'd4', targetId: 'd5', mapId: 'local', capacity: '25g', rxBps: 189000, txBps: 1580000 },
      { id: 'l5', sourceId: 'd5', targetId: 'd6', mapId: 'local', capacity: '10g', rxBps: 0, txBps: 0 },
      { id: 'l6', sourceId: 'd6', targetId: 'd7', mapId: 'local', capacity: '100m', rxBps: 0, txBps: 0 },
      { id: 'l7', sourceId: 'd7', targetId: 'd8', mapId: 'local', capacity: '100m', rxBps: 0, txBps: 0 },
      { id: 'l8', sourceId: 'd5', targetId: 'd9', mapId: 'local', capacity: '1g', rxBps: 0, txBps: 0 },
      { id: 'l9', sourceId: 'd4', targetId: 'd10', mapId: 'local', capacity: '1g', rxBps: 0, txBps: 0 },
      { id: 'l10', sourceId: 'd4', targetId: 'd11', mapId: 'local', capacity: '40g', rxBps: 690000, txBps: 6300000 },
      { id: 'l11', sourceId: 'd11', targetId: 'd12', mapId: 'local', capacity: '10g', rxBps: 0, txBps: 0 },
      { id: 'l12', sourceId: 'd8', targetId: 'sn-norte', mapId: 'local', capacity: '1g', rxBps: 500000, txBps: 200000 },
    ],
  },
  {
    id: 'submap-norte',
    name: 'Sub-rede Norte',
    parentId: 'local',
    devices: [
      {
        id: 'sn1',
        label: 'SW-01',
        ip: '10.0.1.1',
        icon: 'switch',
        status: 'online',
        x: 200,
        y: 180,
        latency: 2,
        uptime: 99.9,
        mapId: 'submap-norte',
      },
      {
        id: 'sn2',
        label: 'SRV-01',
        ip: '10.0.1.10',
        icon: 'server',
        status: 'online',
        x: 400,
        y: 130,
        latency: 1,
        uptime: 100,
        mapId: 'submap-norte',
      },
      {
        id: 'sn3',
        label: 'GW-01',
        ip: '10.0.1.254',
        icon: 'router',
        status: 'warning',
        x: 400,
        y: 280,
        latency: 45,
        uptime: 88.0,
        mapId: 'submap-norte',
      },
    ],
    submapNodes: [],
    badges: [],
    links: [
      { id: 'snl1', sourceId: 'sn1', targetId: 'sn2', mapId: 'submap-norte', capacity: '10g', rxBps: 500000, txBps: 200000 },
      { id: 'snl2', sourceId: 'sn1', targetId: 'sn3', mapId: 'submap-norte', capacity: '1g', rxBps: 100000, txBps: 50000 },
    ],
  },
]
